### ISSUE TITLE
Feature request: Record a distribution for request time

### ISSUE THREAD

**Issue by parsonsmatt** [plow-technologies/yesod-routes-metrics#1]
Oftentimes, a big indicator that something is wrong is a spike in latency for an application. Typically I have to use intuition and guesswork to find the answer, but attaching a timer to each action is a solid way to diagnose what's up.

**Comment by mchaver** [comment]
@parsonsmatt 
[wai-middleware-metrics](https://hackage.haskell.org/package/wai-middleware-metrics-0.2.4/docs/Network-Wai-Metrics.html) provides a latency distribution and is compatible with Yesod and yesod-routes-metrics since you can add multiple pieces of middleware to Wai based apps. Or is there something specific to Yesod that you are looking for?

**Comment by mchaver** [comment]
@parsonsmatt 
I've added some latency metrics with this pull request. It is not very flexible, but if you have some suggestions, please share.
https://github.com/plow-technologies/yesod-routes-metrics/pull/3

**Comment by parsonsmatt** [comment]
That looks awesome! Exactly what I was asking for, thanks :smile:
